# Total planning attempts
max_solutions: 10


# Planning group and link names
arm_group_name: "air"
eef_name: "gripper"
hand_group_name: "gripper"
hand_frame: "qbhand_base_link"

# Poses
hand_open_pose: "open"
hand_close_pose: "full_closed"
arm_home_pose: "home2"

# Scene frames
world_frame: "world"
table_reference_frame: "world"
object_reference_frame: "world"
surface_link: "table"

# Collision object for picking
# CYLINDER object specifications
object_name: "49"
object_dimensions: [0.05, 0.01] # [height, radius]
object_pose: [0.55, -0.25, 0.7, 0, 0, 0]

# Table model
spawn_table: true
table_name: "table"
table_dimensions: [2, 2, 0.001]  # [length, width, height]
table_pose: [0.2, -0.85, 0.65, 0, 0, 0]

# Gripper grasp frame transform [x,y,z,r,p,y]
grasp_frame_transform: [-0.08, 0.124, 0.12, 1.571, 0, 0]

# Place pose [x,y,z,r,p,y]
place_pose: [0.12, -0.7, 0.8, 0, 0, 0]
place_surface_offset: 0.0005 # place offset from table

# Valid distance range when approaching an object for picking
approach_object_min_dist: 0.01
approach_object_max_dist: 0.1

# Valid createObjectheight range when lifting an object after pick
lift_object_min_dist: 0.01
lift_object_max_dist: 0.1
