controller_list:
  - name: fake_air_controller
    type: $(arg fake_execution_type)
    joints:
      - s1j
      - s2j
      - s3j
      - ej
      - rollj
      - pitchj
      - yawj
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - qbhand_synergy_joint
initial:  # Define initial robot poses per group
  - group: air
    pose: home
  - group: gripper
    pose: open