# Settings for ros_control_boilerplate control loop
arm:
    # Publish all joint states
    # Creates the /joint_states topic necessary in ROS
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 100
        joints:
          - s1j
          - s2j
          - s3j
          - ej
          - rollj
          - pitchj
          - yawj
          
    qbhand_joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 100
      
    arm_position_controller:
        type: pos_vel_acc_controllers/JointTrajectoryController
        publish_rate: 100
        joints:
          - s1j
          - s2j
          - s3j
          - ej
          - rollj
          - pitchj
          - yawj
        gains:
          s1j:
            p: 100
            d: 1
            i: 1
            i_clamp: 1
          s2j:
            p: 100
            d: 1
            i: 1
            i_clamp: 1
          s3j:
            p: 100
            d: 1
            i: 1
            i_clamp: 1
          ej:
            p: 100
            d: 1
            i: 1
            i_clamp: 1
          rollj:
            p: 100
            d: 1
            i: 1
            i_clamp: 1
          pitchj:
            p: 100
            d: 1
            i: 1
            i_clamp: 1
          yawj:
            p: 100
            d: 1
            i: 1
            i_clamp: 1
        constraints:
          goal_time: 10.0                  # Override default
          stopped_velocity_tolerance: 0
          s1j:
            goal: 10.0 #0.05 # 3 degree
            trajectory: 10.0 #0.1 # 6 degree
          s2j:
            goal: 10.0 #0.05 # 3 degree
            trajectory: 10.0 #0.1 # 6 degree
          s3j:
            goal: 10.0 #0.05 # 3 degree
            trajectory: 10.0 #0.1 # 6 degree
          ej:
            goal: 10.0 #0.2 # 12 degree
            trajectory: 10.0 #0.25 # 15 degree
          rollj:
            goal: 10.0 #0.1 # 6 degree
            trajectory: 10.0 #0.1 # 6 degree
          pitchj:
            goal: 10.0 #0.1 # 6 degree
            trajectory: 10.0 #0.1 # 6 degree
          yawj:
            goal: 10.0 #0.2 # 12 degree
            trajectory: 10.0 #0.5 # 30 degree

        state_publish_rate:  100            # Override default
        action_monitor_rate: 120           # Override default
        stop_trajectory_duration: 0        # Override default

controller_list:
  - name: arm/arm_position_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - s1j
      - s2j
      - s3j
      - ej
      - rollj
      - pitchj
      - yawj
  - name: /qbhand/control/qbhand_synergy_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - qbhand_synergy_joint
    constraints:  # fake values due to the adaptability
      goal_time: 10.0
      stopped_velocity_tolerance: 100.0
      qbhand_synergy_joint:
        trajectory: 10.0
        goal: 10.0
    state_publish_rate: 100
    action_monitor_rate: 120
    stop_trajectory_duration: 0