sensors:
  - sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
    image_topic: /camera/depth/image_rect_raw
    queue_size: 5
    near_clipping_plane_distance: 0.3
    far_clipping_plane_distance: 2.0
    shadow_threshold: 0.2
    padding_scale: 1.0
    padding_offset: 0.03
    #shape_padding: 0.01
    #shape_scale: 1.0
    max_update_rate: 10
    filtered_cloud_topic: filtered_cloud
    ns: kinect