controller_list:
  - name: fake_air_right_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - s1j
      - s2j
      - s3j
      - ej
      - rollj
      - pitchj
      - yawj
  - name: fake_air_left_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - s1_2j
      - s2_2j
      - s3_2j
      - e_2j
      - roll_2j
      - pitch_2j
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - qbhand_synergy_joint
initial:  # Define initial robot poses per group
  - group: air_right_arm
    pose: right_home
  - group: air_left_arm
    pose: left_home